### ISSUE TITLE
Fix Dead Pieces CSS

### ISSUE THREAD

**Issue by arbrown** [arbrown/pao#28]
PR #27 enlarged the dead pieces container css instead of the dead pieces themselves.  Please adjust the `.dead-pieces .banqi-square` styles in [banqi.css](https://github.com/arbrown/pao/blob/master/client/content/banqi.css#L100) as appropriate and revert the previous change.

**Comment by walrii** [comment]
See PR https://github.com/arbrown/pao/pull/29
