### ISSUE TITLE
Randomize starting player

### ISSUE THREAD

**Issue by arbrown** [arbrown/pao#40]
Currently, the first player to join the game always starts the game.  It should be random or just default to making @perlmonger42 go first in every game.

**Comment by walrii** [comment]
Or we could leave it up to the players. Whoever moves first goes first. This could lead to a race condition, so we should make sure that the first move is transacted.

**Comment by arbrown** [comment]
That's actually an interesting idea.  I think there would be some light refactoring involved (the concept of a next/current player is pretty heavily baked in) but it should be possible.  I don't think the race condition would be an issue, since the client respects whatever game state the server sends it and I think whichever player clicked first would be respected by the server and immediately broadcast to the other player/kibitzers.

**Comment by walrii** [comment]
Unless the server is single threaded, there will be a race condition if two first moves are both being processed on the same game.  I remember that channels or something in GO make that easier to arrange, is that being done?

**Comment by arbrown** [comment]
Right, the game uses goroutines and [channels](https://gobyexample.com/channels) pretty extensively.  In this case, the main game loop consists pretty much of [waiting for and processing commands](https://github.com/arbrown/pao/blob/master/game/game.go#L97) coming in off a channel.  I think if two players flipped up at close to the same time, one would be processed first and then the next would be processed (as long as it wasn't the same piece) since turning up a piece is a perfectly valid second move and it would be the second player's turn.

So... it's not a race condition in the technical sense as I understand the term, but still a condition to be avoided.  Perhaps there could be a 2-second cooldown after the first flip?  That seems like a reasonable solution.

**Comment by perlmonger42** [comment]
I'd been thinking about this myself, and I'd come to the same conclusion:
just accept whoever moves first.
=thom

**Comment by walrii** [comment]
I like the cool down idea.
- reject moves for x seconds (I think 2 might be short)
- display a popup over the board (for 5? seconds)
-- Player BeanCurd went first.
-- BeanCurd is Red
-- Tofu is Black
